---
# tasks file for sudo

- name: Validate provided variables and set os dependent variables
  ansible.builtin.import_tasks: asserts.yml

- name: Import tasks to configure SUDO
  ansible.builtin.import_tasks: sudo.yml
