---
##
# This file provides all tasks related to sudo configuration.
##

- name: Install sudo if not already installed
  ansible.builtin.package:
    name: sudo
    state: present
    update_cache: yes

# Create a new sudoers file
- name: Create new sudoers file
  ansible.builtin.template:
    src: sudoers.j2
    dest: "/etc/sudoers"
    backup: yes
    owner: root
    group: root
    mode: '0440'
    force: true
    validate: /usr/sbin/visudo -cf %s

# Make sure the sudoers file includes the requirement to log to a file
- name: Ensure sudo log file exists
  ansible.builtin.lineinfile:
    path: "/etc/sudoers.d/{{ sudo_config_file_name }}"
    regexp: '^Defaults\s+(log_host,\s*log_year,)?\slogfile='
    line: 'Defaults log_host, log_year, logfile={{ sudo_log }}'
    mode: '0440'
    create: yes
    owner: root
    group: root
    validate: /usr/sbin/visudo -cf %s
  when: sudo_log is defined

- name: Set admin group rule
  vars:
    lstr: "%{{ sudo_admin_group }} ALL=(ALL:ALL)       {{ 'NOPASSWD:' if not sudo_admin_password_required }} ALL"
  ansible.builtin.lineinfile:
    path: "/etc/sudoers.d/{{ sudo_config_file_name }}"
    regexp: "^%{{ sudo_admin_group }} "
    line: "{{ lstr }}"
    mode: '0440'
    create: yes
    owner: root
    group: root
    validate: /usr/sbin/visudo -cf %s
